### PR TITLE
Conditionally load ActiveJob and Rails integrations

### LINKED ISSUE #6668: Confused about `uninitialized constant Sidekiq::ActiveJob` in 7.3.9
Ruby version: 3.4.1
Rails version: 8.0.2
Sidekiq / Pro / Enterprise version(s): 7.3.9

Like seemingly many people (https://github.com/sidekiq/sidekiq/issues/6618, https://github.com/sidekiq/sidekiq/issues/6612, https://github.com/sidekiq/sidekiq/issues/6642, https://github.com/sidekiq/sidekiq/issues/6622) I'm having trouble with upgrading to version 7.3.9.

Reading through those issue it kinda sounds like in a Rails app that has followed the normal installation and setup instructions that things should Just Work, but that doesn't seem to be the case for me.

My app seems to already be doing all of the suggested fixes in those threads. Specifically:

* `gem 'rails'` is listed before `gem 'sidekiq'` in the `Gemfile`
* `require 'rails/all'` is before `Bundler.require(*Rails.groups)` in `config/application.rb`
* `require 'sidekiq'` is in `config/initializers/sidekiq.rb`
* Adding `require 'sidekiq/rails'` to the initializer doesn't make a difference

The two symptoms of the problem that I'm seeing are:

1. `puma` won't start.

```
$ bundle exec puma -C config/puma.rb
[24724] Puma starting in cluster mode...
[24724] * Puma version: 6.6.0 ("Return to Forever")
[24724] * Ruby version: ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [arm64-darwin23]
[24724] *  Min threads: 3
[24724] *  Max threads: 3
[24724] *  Environment: development
[24724] *   Master PID: 24724
[24724] *      Workers: 2
[24724] *     Restarts: (✔) hot (✖) phased
[24724] * Preloading application
[24724] ! Unable to load application: NameError: uninitialized constant Sidekiq::ActiveJob
bundler: failed to load command: puma (/Users/jgreen/.asdf/installs/ruby/3.4.1/bin/puma)
/Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sidekiq-7.3.9/lib/active_job/queue_adapters/sidekiq_adapter.rb:71:in '<class:SidekiqAdapter>': uninitialized constant Sidekiq::ActiveJob (NameError)

      class JobWrapper < Sidekiq::ActiveJob::Wrapper
                                ^^^^^^^^^^^
Did you mean?  ActiveModel
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sidekiq-7.3.9/lib/active_job/queue_adapters/sidekiq_adapter.rb:13:in '<module:QueueAdapters>'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sidekiq-7.3.9/lib/active_job/queue_adapters/sidekiq_adapter.rb:4:in '<module:ActiveJob>'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sidekiq-7.3.9/lib/active_job/queue_adapters/sidekiq_adapter.rb:3:in '<top (required)>'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/zeitwerk-2.7.2/lib/zeitwerk/core_ext/kernel.rb:34:in 'Kernel#require'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activejob-8.0.2/lib/active_job/queue_adapters.rb:136:in 'Module#const_get'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activejob-8.0.2/lib/active_job/queue_adapters.rb:136:in 'ActiveJob::QueueAdapters.lookup'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activejob-8.0.2/lib/active_job/queue_adapter.rb:52:in 'ActiveJob::QueueAdapter::ClassMethods#queue_adapter='
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activejob-8.0.2/lib/active_job/railtie.rb:81:in 'block (3 levels) in <class:Railtie>'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activejob-8.0.2/lib/active_job/railtie.rb:76:in 'Hash#each'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activejob-8.0.2/lib/active_job/railtie.rb:76:in 'block (2 levels) in <class:Railtie>'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.2/lib/active_support/lazy_load_hooks.rb:97:in 'Module#class_eval'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.2/lib/active_support/lazy_load_hooks.rb:97:in 'block in ActiveSupport::LazyLoadHooks#execute_hook'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.2/lib/active_support/lazy_load_hooks.rb:87:in 'ActiveSupport::LazyLoadHooks#with_execution_control'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.2/lib/active_support/lazy_load_hooks.rb:92:in 'ActiveSupport::LazyLoadHooks#execute_hook'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.2/lib/active_support/lazy_load_hooks.rb:62:in 'block in ActiveSupport::LazyLoadHooks#on_load'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.2/lib/active_support/lazy_load_hooks.rb:61:in 'Array#each'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.2/lib/active_support/lazy_load_hooks.rb:61:in 'ActiveSupport::LazyLoadHooks#on_load'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/activejob-8.0.2/lib/active_job/railtie.rb:68:in 'block in <class:Railtie>'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:32:in 'BasicObject#instance_exec'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:32:in 'Rails::Initializable::Initializer#run'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:61:in 'block in Rails::Initializable#run_initializers'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/tsort.rb:231:in 'block in TSort.tsort_each'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/tsort.rb:353:in 'block (2 levels) in TSort.each_strongly_connected_component'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/tsort.rb:434:in 'TSort.each_strongly_connected_component_from'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/tsort.rb:352:in 'block in TSort.each_strongly_connected_component'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/tsort.rb:350:in 'Rails::Initializable::Collection#each'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/tsort.rb:350:in 'Method#call'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/tsort.rb:350:in 'TSort.each_strongly_connected_component'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/tsort.rb:229:in 'TSort.tsort_each'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/tsort.rb:208:in 'TSort#tsort_each'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/railties-8.0.2/lib/rails/initializable.rb:60:in 'Rails::Initializable#run_initializers'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/railties-8.0.2/lib/rails/application.rb:440:in 'Rails::Application#initialize!'
        from /Users/jgreen/projects/shopify-crowdfunder/config/environment.rb:5:in '<top (required)>'
        from config.ru:3:in 'Kernel#require_relative'
        from config.ru:3:in 'block (2 levels) in <top (required)>'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/rack-3.1.12/lib/rack/builder.rb:108:in 'Kernel#eval'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/rack-3.1.12/lib/rack/builder.rb:108:in 'Rack::Builder.new_from_string'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/rack-3.1.12/lib/rack/builder.rb:97:in 'Rack::Builder.load_file'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/rack-3.1.12/lib/rack/builder.rb:67:in 'Rack::Builder.parse_file'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/puma-6.6.0/lib/puma/configuration.rb:386:in 'Puma::Configuration#load_rackup'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/puma-6.6.0/lib/puma/configuration.rb:297:in 'Puma::Configuration#app'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/puma-6.6.0/lib/puma/runner.rb:169:in 'Puma::Runner#load_and_bind'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/puma-6.6.0/lib/puma/cluster.rb:373:in 'Puma::Cluster#run'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/puma-6.6.0/lib/puma/launcher.rb:203:in 'Puma::Launcher#run'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/puma-6.6.0/lib/puma/cli.rb:75:in 'Puma::CLI#run'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/puma-6.6.0/bin/puma:10:in '<top (required)>'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/bin/puma:25:in 'Kernel#load'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/bin/puma:25:in '<top (required)>'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundler/cli/exec.rb:59:in 'Kernel.load'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundler/cli/exec.rb:59:in 'Bundler::CLI::Exec#kernel_load'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundler/cli.rb:452:in 'Bundler::CLI#exec'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor.rb:538:in 'Bundler::Thor.dispatch'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundler/cli.rb:29:in 'Bundler::CLI.start'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/bundler-2.6.2/exe/bundle:28:in 'block in <top (required)>'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/3.4.0/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/bundler-2.6.2/exe/bundle:20:in '<top (required)>'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/bin/bundle:25:in 'Kernel#load'
        from /Users/jgreen/.asdf/installs/ruby/3.4.1/bin/bundle:25:in '<main>'
```

2. `rspec` can't get past the loading phase:

```
$ bundle exec rspec spec/controllers/css_controller_spec.rb

An error occurred while loading ./spec/controllers/css_controller_spec.rb.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

NameError:
  uninitialized constant Sidekiq::ActiveJob
# ./config/environment.rb:5:in '<top (required)>'
# ./spec/rails_helper.rb:3:in '<top (required)>'
# ./spec/controllers/css_controller_spec.rb:1:in '<top (required)>'
No examples found.


Finished in 0.00003 seconds (files took 1.27 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

Have I overlooked something in one of those threads?

### PR DESCRIPTION
**Pull request by seuros**
Remove the assumption that Rails will be installed from the meta gem or granular with ActiveJob.

- A script could be using ActiveJob in standalone and won't need Rails initialization
- A Rails application could have Sidekiq and not use the ActiveJob wrapper to reduce dependencies

This change wraps relevant code in `if defined?` checks to ensure Sidekiq only loads what's needed based on the actual environment dependencies.

Fixes #6668

### CODE REVIEW

File: lib/sidekiq.rb [hunk 1]
```diff
@@ -146,4 +146,4 @@ def self.configure_client
   class Shutdown < Interrupt; end
 end
 
-require "sidekiq/rails" if defined?(::Rails::Engine)
+require "sidekiq/rails"
```
Comment (seuros) [inline lib/sidekiq.rb:149]: This will be a NOP if both AJ and Rails are not loaded before sidekiq.

File: lib/sidekiq/rails.rb [hunk 2]
```diff
@@ -1,42 +1,9 @@
 # frozen_string_literal: true
 
 require "sidekiq/job"
-require "rails"
```
Comment (seuros) [inline lib/sidekiq/rails.rb:4]: i removed this require since Railtie was already defining Rails::Engine

File: lib/sidekiq/rails.rb [hunk 3]
```diff
@@ -48,34 +15,65 @@ def to_hash
     #     def perform
     #     end
     #   end
-    initializer "sidekiq.active_job_integration" do
-      ActiveSupport.on_load(:active_job) do
-        require_relative "../active_job/queue_adapters/sidekiq_adapter"
-        include ::Sidekiq::Job::Options unless respond_to?(:sidekiq_options)
+    require_relative "../active_job/queue_adapters/sidekiq_adapter"
+    ::ActiveJob::Base.include ::Sidekiq::Job::Options unless ::ActiveJob::Base.respond_to?(:sidekiq_options)
```
Comment (seuros) [inline lib/sidekiq/rails.rb:19]: This was removed from the initialiser to as it AJ specific.

**Comment by mperham** [comment]
Can you reproduce the issue locally? Did you test that this fixes the issue?

**Comment by jagthedrummer** [comment]
A bunch of tests here are failing with the same error from #6668.

```
uninitialized constant Sidekiq::ActiveJob
```

**Comment by seuros** [comment]
@mperham I've arranged the code to work with the cases we discussed.
The implementation now has two key improvements:

For ActiveJob integration:

If the application is bundled with activejob (≥ 7.0), Sidekiq will require it and patch the adapter
This happens in the sidekiq_adapter file with its own version checking

For Rails integration:

If rails(≥ 7.0) is detected, Sidekiq will require rails to define the initializers.

The gem method provides automatic version requirement checking.

**Comment by mperham** [comment]
Is there any Rails core member who can review this? I want to understand if there is a "right" way to conditionally load code.

I wonder if we should always load `Sidekiq::ActiveJob::Wrapper`, even if not running in Rails. It's a tiny class with no dependencies. Would that fix the issue?

**Review by mperham — APPROVED** [review]

**Comment by seuros** [comment]
I was part of the effort that build AJ.

The changed wrapper adds features not normally in ActiveJob. 

The original wrapper didn't let you send options to Sidekiq. We focused on the opensource version, not the Pro with unique jobs ect. Back then, Sidekiq Enterprise didn't exist yet. 

Later, Sidekiq Pro users had to use both /jobs and /workers folders for different job types, which was annoying because job code was in two places or mixed with different syntax.


In this [gist](https://gist.github.com/seuros/dec6e0b3c0df682666dc9ef565b93b94) , you can see a job can run without using Railties. Since Railtie isn't detected, you must set up ActiveJob:Base directly to use sidekiq.

If you use this PR branch, you can use all ActiveJob features, including Sidekiq Pro/Enterprise options. 

But with older versions before this PR, Sidekiq options aren't added unless you include the Railtie gem or another gem that needs it.


In Other hand, the sidekiq adapter in rails is deprecated and will be remove . @fatkodima has a PR opened.

**Comment by mperham** [comment]
I think I understand and I like the direction. Thanks for the explanation. 😎

**Comment by seuros** [comment]
@mperham should we merge ?
